<a href="https://colab.research.google.com/github/kisung2577/CMPE-258/blob/main/2b_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
# Scalar vector multiplication

a = torch.rand(1)
b = torch.rand(4, 6)
mult = torch.einsum('i, ij -> ij', [a, b])
print(a)
print(b)
print(mult)

tensor([0.2816])
tensor([[0.7502, 0.7038, 0.7051, 0.9726, 0.0451, 0.4314],
        [0.2282, 0.5770, 0.8642, 0.1719, 0.1312, 0.9539],
        [0.6936, 0.5727, 0.7348, 0.8307, 0.7632, 0.1978],
        [0.0399, 0.2240, 0.5388, 0.7339, 0.8331, 0.6872]])
tensor([[0.2113, 0.1982, 0.1986, 0.2739, 0.0127, 0.1215],
        [0.0643, 0.1625, 0.2434, 0.0484, 0.0370, 0.2687],
        [0.1954, 0.1613, 0.2070, 0.2340, 0.2150, 0.0557],
        [0.0112, 0.0631, 0.1517, 0.2067, 0.2346, 0.1935]])


In [ ]:
# Vector vector multiplication

a = torch.rand(1, 2)
b = torch.rand(2, 3)
mult = torch.einsum('ij, jk -> ik', [a, b])
print(a)
print(b)
print(mult)

tensor([[0.0365, 0.0465]])
tensor([[0.1035, 0.9038, 0.0463],
        [0.4622, 0.4749, 0.1414]])
tensor([[0.0253, 0.0551, 0.0083]])


In [ ]:
# Outer product

a = torch.arange(5)
b = torch.arange(3, 6)  
prod = torch.einsum('i,j -> ij', [a, b])
print(a)
print(b)
print(prod)

tensor([0, 1, 2, 3, 4])
tensor([3, 4, 5])
tensor([[ 0,  0,  0],
        [ 3,  4,  5],
        [ 6,  8, 10],
        [ 9, 12, 15],
        [12, 16, 20]])


In [ ]:
# Scalar dot product

a = torch.arange(9).reshape(3, 3)
b = torch.arange(6).reshape(3, 2)
prod = torch.einsum('ij, jk ->', [a, b])
print(a)
print(b)
print(prod)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor(204)


In [ ]:
# Hadamard product

a = torch.arange(8).reshape(2, 4)
b = torch.arange(4, 12).reshape(2, 4)
prod = torch.einsum('ij, ij -> ij', [a, b])
print(a)
print(b)
print(prod)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  5, 12, 21],
        [32, 45, 60, 77]])


In [ ]:
# Batch matrix multiplication

a = torch.randn(3, 3, 5)
b = torch.randn(3, 5, 2)
batch_mult = torch.einsum('bij, bjk -> bik', [a, b])
print(a)
print(b)
print(batch_mult)

tensor([[[ 0.1146, -1.5396, -0.1097,  1.0692,  0.1926],
         [ 0.5118,  0.0285, -0.9787,  1.2378, -0.1649],
         [ 0.7038, -0.9669,  1.2838, -0.3901, -1.6070]],

        [[-1.1492,  0.4336, -1.1261,  0.6780,  0.4498],
         [ 0.8887,  0.3932,  0.1344,  0.3686, -1.2185],
         [ 0.6003,  0.6075, -0.6520,  0.1858, -0.1856]],

        [[ 0.2790,  1.0010,  1.0151,  0.2252,  0.6820],
         [ 1.3085,  2.5153,  0.8193, -0.2701,  0.7210],
         [-1.2182, -0.1762, -0.3039, -0.6304, -1.0085]]])
tensor([[[-0.1038,  0.3215],
         [ 0.9147, -2.5490],
         [-0.8357,  0.7215],
         [ 0.0268,  0.8814],
         [ 1.4209, -0.9968]],

        [[-0.2211, -0.2287],
         [ 1.0892, -0.3269],
         [-0.7064, -0.9105],
         [ 0.1062,  0.9049],
         [ 0.0365, -0.7387]],

        [[ 0.5233,  0.5796],
         [-1.6353, -1.0672],
         [-2.3501,  1.4199],
         [ 0.7197,  1.4262],
         [-1.6448,  2.9994]]])
tensor([[[-1.0262,  4.6326],
         [ 0.5897,  

In [ ]:
# Tensor reduction

a = torch.randn(2, 3, 5, 7)
b = torch.randn(4, 1, 3, 11, 5)
reduction = torch.einsum('pqrs, tuqvr -> pstuv', [a, b])
print(a.shape, b.shape, reduction.shape)

torch.Size([2, 3, 5, 7]) torch.Size([4, 1, 3, 11, 5]) torch.Size([2, 7, 4, 1, 11])


In [ ]:
# Transpose

a = torch.arange(8).reshape(4, 2)
transpose = torch.einsum('ij -> ji', [a])
print(a)
print(transpose)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])
tensor([[0, 2, 4, 6],
        [1, 3, 5, 7]])


In [ ]:
# Bilinear transformation

a = torch.randn(2, 3)
b = torch.randn(3, 3, 4)
c = torch.randn(2, 4)
bilinear = torch.einsum('ik, jkl, il -> ij', [a, b, c])
print(a)
print(b)
print(c)
print(bilinear)

tensor([[-0.3459, -0.1460, -0.7323],
        [ 0.5967,  0.1398,  0.5191]])
tensor([[[-1.3349, -0.7883,  0.3478,  0.3982],
         [ 1.2176,  0.7449, -0.0551, -1.1972],
         [-1.5638,  0.4705,  0.4891,  1.5464]],

        [[ 1.1694,  1.2269,  1.2733,  0.3802],
         [-0.5719,  0.6567,  0.9136, -0.6088],
         [ 0.0022,  0.7988,  0.5315,  1.0724]],

        [[-0.0579,  0.3398,  0.3263,  0.1343],
         [ 0.6590, -0.6689,  0.9644,  0.8690],
         [ 0.3517, -0.7693,  1.2730, -0.4861]]])
tensor([[ 0.7735,  0.5377, -1.3788,  0.4021],
        [ 0.5709,  0.5487, -0.8845, -1.5437]])
tensor([[ 1.2165,  0.1512,  1.7427],
        [-2.6373, -1.0743, -0.8197]])


In [ ]:
# Attention

def random_tensors(shape, num=1, requires_grad=False):
  tensors = [torch.randn(shape, requires_grad=requires_grad) for i in range(0, num)]
  return tensors[0] if num == 1 else tensors

# Parameters
# [hidden_dimension]
bM, br, w = random_tensors([7], num=3, requires_grad=True)
# [hidden_dimension x hidden_dimension]
WY, Wh, Wr, Wt = random_tensors([7, 7], num=4, requires_grad=True)

def attention(Y, ht, rt1):
  # [batch_size x hidden_dimension] 
  tmp = torch.einsum('ik, kl -> il', [ht, Wh]) + torch.einsum('ik, kl -> il', [rt1, Wr])

  Mt = torch.tanh(torch.einsum('ijk, kl -> ijl', [Y, WY]) + tmp.unsqueeze(1).expand_as(Y) + bM)
  
  # [batch_size x sequence_length]
  at = torch.nn.functional.softmax(torch.einsum('ijk, k -> ij', [Mt, w])) 
  
  # [batch_size x hidden_dimension]
  rt = torch.einsum('ijk, ij -> ik', [Y, at]) + torch.tanh(torch.einsum('ij, jk -> ik', [rt1, Wt]) + br)
  
  return rt, at

# Inputs - [batch_size x sequence_length x hidden_dimension]
Y = torch.randn(3,5,7)
# [batch_size x hidden_dimension]
ht, rt1 = random_tensors([3, 7], num=2)

rt, at = attention(Y, ht, rt1)

print(at)

tensor([[0.0089, 0.0552, 0.4351, 0.5002, 0.0006],
        [0.0122, 0.0339, 0.3530, 0.0084, 0.5925],
        [0.1238, 0.1239, 0.2828, 0.1251, 0.3444]], grad_fn=<SoftmaxBackward0>)


<ipython-input-11-0f495568e4dc>:20: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  at = torch.nn.functional.softmax(torch.einsum('ijk, k -> ij', [Mt, w]))


In [ ]:
# Treeqn

def transition(zl):
  # [batch_size x num_actions x hidden_dimension]
  return zl.unsqueeze(1) + torch.tanh(torch.einsum('bk, aki -> bai', [zl, W]) + b)

# Inputs - [batch_size x hidden_dimension]
zl = torch.randn(2, 3)
# Parameters - [num_actions x hidden_dimension]
b = torch.randn(5, 3)
# Actions - [num_actions x hidden_dimension x hidden_dimension]
W = torch.randn(5, 3, 3)

transition(zl)

tensor([[[-1.6990e+00, -2.1557e-01,  5.2023e-01],
         [-2.0484e-02, -1.2507e+00,  5.6257e-01],
         [ 1.5275e-01, -1.8896e-02,  1.7447e+00],
         [-1.6518e+00, -7.0626e-04,  1.8144e+00],
         [-7.5640e-02, -1.3509e+00,  2.0551e+00]],

        [[ 7.1370e-01,  1.7903e-01,  4.0921e-02],
         [ 2.2022e+00, -1.2305e-01,  1.2058e+00],
         [ 2.2360e+00, -2.9854e-01,  1.2327e+00],
         [ 1.8857e+00, -1.8142e+00,  1.3945e+00],
         [ 2.0408e+00, -1.5949e+00, -9.2836e-02]]])