<a href="https://colab.research.google.com/github/kisung2577/CMPE-258/blob/main/2b_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Scalar vector multiplication

a = np.array([3])
b = np.array([2, 4, 5])
mult = np.einsum('i, i -> i', a, b)
print(a)
print(b)
print(mult)

[3]
[2 4 5]
[ 6 12 15]


In [ ]:
# Vector vector multiplication

a = np.random.randn(2, 4)
b = np.random.randn(4, 3)
mult = np.einsum('ij, jk -> ik', a, b)
print(a)
print(b)
print(mult)

[[-0.00338652 -0.52004263 -0.79945164 -1.34850146]
 [-0.19883934 -0.80090957 -1.56811686  1.84009868]]
[[ 1.19780323  1.51750588 -0.92404393]
 [-1.57687202 -1.28682156  0.27996047]
 [ 0.89980632 -0.72144876 -2.05001009]
 [ 0.98495439  0.40051464 -1.58427072]]
[[-1.23157978  0.70073182  3.63281322]
 [ 1.42617331  2.59719027  0.25895418]]


In [ ]:
# Outer product

a = np.arange(1, 4)
b = np.arange(3, 6)  
prod = np.einsum('i,j -> ij', a, b)
print(a)
print(b)
print(prod)

[1 2 3]
[3 4 5]
[[ 3  4  5]
 [ 6  8 10]
 [ 9 12 15]]


In [ ]:
# Scalar dot product

a = np.arange(9).reshape(3, 3)
b = np.arange(6).reshape(3, 2)
prod = np.einsum('ij, jk ->', a, b)
print(a)
print(b)
print(prod)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [2 3]
 [4 5]]
204


In [ ]:
# Hadamard product

a = np.arange(8).reshape(2, 4)
b = np.arange(4, 12).reshape(2, 4)
prod = np.einsum('ij, ij -> ij', a, b)
print(a)
print(b)
print(prod)

[[0 1 2 3]
 [4 5 6 7]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  5 12 21]
 [32 45 60 77]]


In [ ]:
# Batch matrix multiplication

a = np.random.randn(3, 3, 2)
b = np.random.randn(3, 2, 2)
batch_mult = np.einsum('bij, bjk -> bik', a, b)
print(a)
print(b)
print(batch_mult)

[[[-0.63076012  1.00914109]
  [ 1.88456338 -0.44343745]
  [ 0.10799052  0.97722733]]

 [[ 0.89348979 -0.3491128 ]
  [ 0.31415594  0.56329561]
  [ 0.86966602  0.88046334]]

 [[ 0.81926236 -0.69685057]
  [ 0.16912912 -1.91777209]
  [ 0.8531975   1.58821208]]]
[[[ 0.25332386 -0.15025246]
  [-0.83064993  1.30635767]]

 [[-0.63080076  1.77141133]
  [-1.60835342 -0.40780997]]

 [[-1.62385013 -0.76012173]
  [ 1.09193228 -1.67468762]]]
[[[-9.98029559e-01  1.41307246e+00]
  [ 8.45746154e-01 -8.62448198e-01]
  [-7.84377230e-01  1.26038257e+00]]

 [[-2.11728143e-03  1.72510962e+00]
  [-1.10414823e+00  3.26781825e-01]
  [-1.96468221e+00  1.18147451e+00]]

 [[-2.09127293e+00  5.44267895e-01]
  [-2.36871760e+00  3.08311046e+00]
  [ 3.48755169e-01 -3.30829305e+00]]]


In [ ]:
# Tensor reduction

a = np.random.randn(2, 3, 5, 7)
b = np.random.randn(4, 1, 3, 11, 5)
reduction = np.einsum('pqrs, tuqvr -> pstuv', a, b)
print(a.shape, b.shape, reduction.shape)

(2, 3, 5, 7) (4, 1, 3, 11, 5) (2, 7, 4, 1, 11)


In [ ]:
# Transpose

a = np.arange(8).reshape(4, 2)
transpose = np.einsum('ij -> ji', a)
print(a)
print(transpose)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 2 4 6]
 [1 3 5 7]]


In [ ]:
# Bilinear transformation

a = np.random.randn(2, 3)
b = np.random.randn(3, 3, 4)
c = np.random.randn(2, 4)
bilinear = np.einsum('ik, jkl, il -> ij', a, b, c)
print(a)
print(b)
print(c)
print(bilinear)

[[-1.4485944   0.55887873 -2.62459252]
 [ 0.8559395   2.59987455 -1.42999501]]
[[[-0.54927212  0.17903394  0.2014629   0.03917421]
  [-0.72322818  0.45718757  1.43569689  0.50849107]
  [ 0.26767527  1.34071031 -0.82566379 -0.66827142]]

 [[ 2.49446094 -0.73595566 -0.70024972 -0.0103839 ]
  [ 0.92078244  1.16321481 -0.68400726  0.22027506]
  [ 0.41928042 -0.37746651 -1.67376953 -0.02967343]]

 [[-0.03569245  0.13793576  1.32990835 -0.00434988]
  [-1.46486173  0.49473248 -1.39964611  1.46589578]
  [-0.86498001  0.16806743  0.42753547 -1.30813548]]]
[[-0.39227401 -0.20273234  0.2477246  -0.14672633]
 [ 0.43258626 -1.04729208  0.01067211  0.25972644]]
[[ 1.20875817  2.31163481 -2.08968511]
 [ 0.07473915 -1.2153595  -0.90311826]]


In [ ]:
# Attention

# Parameters
# [hidden_dimension]
bM = np.random.randn(7)
br = np.random.randn(7) 
w = np.random.randn(7)
# [hidden_dimension x hidden_dimension]
WY = np.random.randn(7, 7)
Wh = np.random.randn(7, 7)
Wr = np.random.randn(7, 7)
Wt = np.random.randn(7, 7)

def attention(Y, ht, rt1):
  # [batch_size x hidden_dimension] 
  tmp = np.einsum('ik, kl -> il', ht, Wh) + np.einsum('ik, kl -> il', rt1, Wr)

  tmp_expanded = np.expand_dims(tmp, 1)
  tmp_tiled = np.tile(tmp_expanded, [1, Y.shape[1], 1]) 
  Mt = np.tanh(np.einsum('ijk, kl -> ijl', Y, WY) + tmp_tiled + bM)
  
  # [batch_size x sequence_length]
  at = np.einsum('ijk, k -> ij', Mt, w)
  at = np.exp(at)/np.sum(np.exp(at))
  
  # [batch_size x hidden_dimension]
  rt = np.einsum('ijk, ij -> ik', Y, at) + np.tanh(np.einsum('ij, jk -> ik', rt1, Wt) + br)
  
  return rt, at

# Inputs - [batch_size x sequence_length x hidden_dimension]
Y = np.random.randn(3,5,7)
# [batch_size x hidden_dimension]
ht = np.random.randn(3, 7)
rt1 = np.random.randn(3, 7)

rt, at = attention(Y, ht, rt1)

print(at)

[[5.47125812e-04 2.28926215e-03 6.91404338e-03 2.59498241e-03
  3.09866300e-04]
 [5.79239575e-03 1.57265700e-02 4.45565438e-03 2.63792353e-03
  4.55725721e-03]
 [4.29491981e-01 1.73101541e-01 6.68868033e-02 1.30561439e-01
  1.54133155e-01]]


In [ ]:
# Treeqn

def transition(zl):
  # [batch_size x num_actions x hidden_dimension]
  return np.expand_dims(zl, 1) + np.tanh(np.einsum('bk, aki -> bai', zl, W) + b)

# Inputs - [batch_size x hidden_dimension]
zl = np.random.rand(2, 3)
# Parameters - [num_actions x hidden_dimension]
b = np.random.rand(5, 3)
# Actions - [num_actions x hidden_dimension x hidden_dimension]
W = np.random.rand(5, 3, 3)

transition(zl)

array([[[0.58320689, 1.20307567, 0.83216163],
        [0.62859962, 1.03290905, 0.54467109],
        [0.68747555, 0.78291113, 0.39386395],
        [0.73146644, 1.17128639, 0.85214295],
        [0.35983477, 1.24340611, 0.69242728]],

       [[1.54465543, 1.6016828 , 1.64602312],
        [1.62968541, 1.60709961, 1.55287599],
        [1.62526219, 1.36889805, 1.29103008],
        [1.6106972 , 1.68072835, 1.56289925],
        [1.41939064, 1.66450216, 1.5679081 ]]])