In [ ]:
import tensorflow as tf


In [ ]:
# Scalar vector multiplication

a = tf.random.normal([1])
b = tf.random.normal([2, 3])
mult = tf.einsum('k, ij -> ij', a, b)
print(a)
print(b)
print(mult)

tf.Tensor([-0.55923367], shape=(1,), dtype=float32)
tf.Tensor(
[[-1.1023293   0.33324072 -1.2455174 ]
 [ 0.79800516 -1.1797341  -0.07181134]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.6164596  -0.18635944  0.6965352 ]
 [-0.44627136  0.659747    0.04015932]], shape=(2, 3), dtype=float32)


In [ ]:
# Vector vector multiplication

a = tf.random.normal([2, 5])
b = tf.random.normal([5, 3])
mult = tf.einsum('ij, jk -> ik', a, b)
print(a)
print(b)
print(mult)

tf.Tensor(
[[-0.7884673  -0.6269408  -0.33551803  1.7072662  -1.7983615 ]
 [-0.14004499 -0.4285374  -0.5425796  -0.5551405  -0.07396466]], shape=(2, 5), dtype=float32)
tf.Tensor(
[[ 0.3807802   0.20056583 -0.20291573]
 [-0.09050325  0.03314591  1.3765222 ]
 [-2.013994    0.98591244  0.6424759 ]
 [ 0.5483715   1.6944003   0.15718229]
 [ 0.5761126  -1.5991565  -0.54028946]], shape=(5, 3), dtype=float32)
tf.Tensor(
[[ 0.33239603  5.2589426   0.32142007]
 [ 0.73117447 -1.3995777  -0.95736414]], shape=(2, 3), dtype=float32)


In [ ]:
# Outer product

a = tf.range(4)
b = tf.range(3, 6)  
prod = tf.einsum('i,j -> ij', a, b)
print(a)
print(b)
print(prod)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
tf.Tensor([3 4 5], shape=(3,), dtype=int32)
tf.Tensor(
[[ 0  0  0]
 [ 3  4  5]
 [ 6  8 10]
 [ 9 12 15]], shape=(4, 3), dtype=int32)


In [ ]:
# Scalar dot product

a = tf.range(9)
a = tf.reshape(a, [3, 3])

b = tf.range(6)
b = tf.reshape(b, [3, 2])

prod = tf.einsum('ij, jk ->', a, b)
print(a)
print(b)
print(prod)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 1]
 [2 3]
 [4 5]], shape=(3, 2), dtype=int32)
tf.Tensor(204, shape=(), dtype=int32)


In [ ]:
# Hadamard product

a = tf.range(8)
a = tf.reshape(a, [2, 4])

b = tf.range(4, 12)
b = tf.reshape(b, [2, 4])

prod = tf.einsum('ij, ij -> ij', a, b)
print(a)
print(b)
print(prod)

tf.Tensor(
[[0 1 2 3]
 [4 5 6 7]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 4  5  6  7]
 [ 8  9 10 11]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 0  5 12 21]
 [32 45 60 77]], shape=(2, 4), dtype=int32)


In [ ]:
# Batch matrix multiplication

a = tf.random.normal([3, 3, 2])
b = tf.random.normal([3, 2, 2])
batch_mult = tf.einsum('bij, bjk -> bik', a, b)
print(a)
print(b)
print(batch_mult)

tf.Tensor(
[[[ 1.0395631   1.1407069 ]
  [ 1.0907776  -0.5415831 ]
  [-1.9870127   1.848457  ]]

 [[ 0.7466669   0.60055065]
  [ 0.65722996  0.44454777]
  [-0.38242555  0.89977026]]

 [[ 0.1432369  -0.4709137 ]
  [ 1.0564594  -0.91324335]
  [-0.41943967  0.98119724]]], shape=(3, 3, 2), dtype=float32)
tf.Tensor(
[[[ 0.21024947 -0.92329884]
  [-1.0918292  -1.6755234 ]]

 [[ 1.7064507   1.7835519 ]
  [ 0.7112839  -0.5586327 ]]

 [[ 0.4940715  -0.30723324]
  [ 0.07450745  0.09177897]]], shape=(3, 2, 2), dtype=float32)
tf.Tensor(
[[[-1.0268894  -2.8711085 ]
  [ 0.8206517  -0.09967852]
  [-2.4359674  -1.2625264 ]]

 [[ 1.7013123   0.9962319 ]
  [ 1.4377302   0.92386484]
  [-0.01259822 -1.1847169 ]]

 [[ 0.0356827  -0.08722711]
  [ 0.4539231  -0.40839598]
  [-0.1341267   0.21891908]]], shape=(3, 3, 2), dtype=float32)


In [ ]:
# Tensor reduction

a = tf.random.normal([2, 3, 5, 7])
b = tf.random.normal([4, 1, 3, 11, 5])
reduction = tf.einsum('pqrs, tuqvr -> pstuv', a, b)
print(a.shape, b.shape, reduction.shape)

(2, 3, 5, 7) (4, 1, 3, 11, 5) (2, 7, 4, 1, 11)


In [ ]:
# Transpose

a = tf.range(8)
a = tf.reshape(a, [4, 2])
transpose = tf.einsum('ij -> ji', a)
print(a)
print(transpose)

tf.Tensor(
[[0 1]
 [2 3]
 [4 5]
 [6 7]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[0 2 4 6]
 [1 3 5 7]], shape=(2, 4), dtype=int32)


In [ ]:
# Bilinear transformation

a = tf.random.normal([2, 3])
b = tf.random.normal([3, 3, 4])
c = tf.random.normal([2, 4])
bilinear = tf.einsum('ik, jkl, il -> ij', a, b, c)
print(a)
print(b)
print(c)
print(bilinear)

tf.Tensor(
[[-0.28493285 -0.95368487 -0.579292  ]
 [ 0.40273324 -0.04913734  0.96179605]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[-0.7630068  -0.15874855 -2.657755    0.9764125 ]
  [ 0.68923306  1.7599032  -0.01813803  0.31981573]
  [ 1.2648927  -0.27811274 -1.3007429  -0.23362596]]

 [[-0.10046025  1.7531148   1.8616902   3.0963306 ]
  [-0.28033784 -0.13925868  0.15269974 -1.420734  ]
  [-0.3030878  -0.41626033  1.0835896   0.7766555 ]]

 [[-1.0867088   0.1069622   1.0848429  -0.46706915]
  [-0.612039   -1.6983812   1.3262333   0.52217007]
  [-2.3989346  -0.5514938  -0.3897668   0.5663083 ]]], shape=(3, 3, 4), dtype=float32)
tf.Tensor(
[[-0.31668934 -0.41151023  1.654815    1.3993987 ]
 [ 0.9255665  -0.2483545  -0.726858   -1.7269483 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 2.8790753 -2.2233343 -4.7090926]
 [ 2.3368225 -5.2332287 -2.981662 ]], shape=(2, 3), dtype=float32)


In [ ]:
# Attention

# Parameters
# [hidden_dimension]
bM = tf.random.normal([7])
br = tf.random.normal([7]) 
w = tf.random.normal([7])
# [hidden_dimension x hidden_dimension]
WY = tf.random.normal([7, 7])
Wh = tf.random.normal([7, 7])
Wr = tf.random.normal([7, 7])
Wt = tf.random.normal([7, 7])

def attention(Y, ht, rt1):
  # [batch_size x hidden_dimension] 
  tmp = tf.einsum('ik, kl -> il', ht, Wh) + tf.einsum('ik, kl -> il', rt1, Wr)

  tmp_expanded = tf.expand_dims(tmp, 1)
  tmp_tiled = tf.tile(tmp_expanded, [1, Y.shape[1], 1]) 
  Mt = tf.tanh(tf.einsum('ijk, kl -> ijl', Y, WY) + tmp_tiled + bM)
  
  # [batch_size x sequence_length]
  at = tf.nn.softmax(tf.einsum('ijk, k -> ij', Mt, w)) 
  
  # [batch_size x hidden_dimension]
  rt = tf.einsum('ijk, ij -> ik', Y, at) + tf.tanh(tf.einsum('ij, jk -> ik', rt1, Wt) + br)
  
  return rt, at

# Inputs - [batch_size x sequence_length x hidden_dimension]
Y = tf.random.normal([3,5,7])
# [batch_size x hidden_dimension]
ht = tf.random.normal([3, 7])
rt1 = tf.random.normal([3, 7])

rt, at = attention(Y, ht, rt1)

print(at)

tf.Tensor(
[[0.04229969 0.3735868  0.11959195 0.02485568 0.43966585]
 [0.95810163 0.01335151 0.00430042 0.02068932 0.00355718]
 [0.07571151 0.01765453 0.42231393 0.07351857 0.4108015 ]], shape=(3, 5), dtype=float32)


In [ ]:
# Treeqn

def transition(zl):
  # [batch_size x num_actions x hidden_dimension]
  return tf.expand_dims(zl, 1) + tf.tanh(tf.einsum('bk, aki -> bai', zl, W) + b)

# Inputs - [batch_size x hidden_dimension]
zl = tf.random.normal([2, 3])
# Parameters - [num_actions x hidden_dimension]
b = tf.random.normal([5, 3])
# Actions - [num_actions x hidden_dimension x hidden_dimension]
W = tf.random.normal([5, 3, 3])

transition(zl)

<tf.Tensor: shape=(2, 5, 3), dtype=float32, numpy=
array([[[-0.6032957 , -0.892448  ,  0.9411356 ],
        [-0.23094764,  0.83399975,  2.9380612 ],
        [-0.6054882 ,  0.23978196,  2.6229339 ],
        [ 0.9175006 , -0.5770587 ,  2.8433683 ],
        [-0.58483374, -1.1329799 ,  1.9702685 ]],

       [[-1.8698051 , -1.2841662 , -1.2184174 ],
        [-0.38783342, -1.483618  , -1.1323792 ],
        [-0.37965512,  0.41943192,  0.6764093 ],
        [-1.8789537 , -1.5598006 , -1.2836028 ],
        [-0.10914898,  0.38269866, -1.3163538 ]]], dtype=float32)>